### ISSUE TITLE
Possibility to directly install the Cloud Integration in the main composer.

### ISSUE THREAD

**Issue by azngeek** [shopgate/cloud-integration-magento#58]
I would like to directly use the project composer to install the Shopgate-Plugins.

```
    "shopgate/cart-integration-magento": "2.9.67",
    "shopgate/cloud-integration-magento": "3.1.1"
```

Currently all the required dependencies do not get resolved completely (e.g die OAuth-Extension is missing) and also the Extension will not be moved into the default Magento-Location for .modman Extensions. This could be resolved by adding the magento-hackathon dependencies into the project description.

```
    "magento-hackathon/magento-composer-installer": "*",
```

However if this is not possible for any reason could you describe your process of setting up an developer-friendly environment where we could use ```modman``` to deploy all the required packages?

**Comment by augsteyer** [comment]
With the current versions of these plugins it seems to be not possible. What needs to be (will be) done for the upcoming version releases to add `"type": "magento-module",` to the composer files. This is the reason why the modules are not deployed to their respective folders right now.

The oAuth dependency is not easily resolvable due to not having all of our merchants using composer to handle dependencies like oAuth2 that we have over there. Hence why this is a small hack to put it in the Lib folder & autoload it ourselves. Once we release the new version of the cloud plugin, the process will be:
```
composer require shopgate/cloud-integration-magento="~3.1.2"
cd vendor/shopgate/cloud-integration-magento/src/lib/Shopgate/cloud-integration-magento-oauth2/
composer update

# if you have 'copy' as deployment strategy
cd ../../../../../../../
composer run-script post-install-cmd -vvv -- --redeploy
```

**Comment by augsteyer** [comment]
Issue is handled in PR #59
